apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: dataproduct-target-group
  namespace: nada
spec:
  image: {{ image }}
  schedule: '11 5 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 2
  concurrencyPolicy: Forbid
  env:
    - name: SOURCE_AUDIT_LOGS_TABLE
      value: nada-prod-6977.bigquery_audit_logs_org.cloudaudit_googleapis_com_data_access
  accessPolicy:
    outbound:
      rules:
        - application: nada-backend
  gcp:
    bigQueryDatasets:
    - description: Metrikker på konsum av dataprodukter
      name: platform_users
      permission: READWRITE
