apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: datamarkedsplassen-dataprodukter
  namespace: nada
spec:
  image: {{ image }}
  command:
    - python
    - etl/alt_stage_to_dp.py
  schedule: '0 9 * * *'
  env:
    - name: BQ_TABLE_URI
      value: nada-prod-6977.bq_metrics_datamarkedsplassen.dataproducts
  gcp:
    bigQueryDatasets:
    - description: Metrikker på konsum av datapakker
      name: bq_metrics_datamarkedsplassen
      permission: READWRITE
