apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: metrics-markedsplassen
  namespace: nada
spec:
  image: {{ image }}
  schedule: '0 8 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 2
  concurrencyPolicy: Forbid
  envFrom:
    - secret: google-sql-nada-backend
  env:
    - name: SOURCE_AUDIT_LOGS_TABLE
      value: nada-prod-6977.bigquery_audit_logs_org.cloudaudit_googleapis_com_data_access
    - name: STAGE_TABLE
      value: {{stage_table}}
    - name: DATAPRODUCTS_TABLE
      value: {{dp_table}}
    - name: CLOUD_SQL_INSTANCE
      value: nada-backend
    - name: NADA_BACKEND_URL
      value: http://nada-backend/api/query
  accessPolicy:
    outbound:
      rules:
        - application: nada-backend
  gcp:
    bigQueryDatasets:
    - description: Metrikker på konsum av dataprodukter
      name: bq_metrics_datamarkedsplassen
      permission: READWRITE
    - name: bigquery_audit_logs_org
      permission: READ
