name: Deploy metrics dataproduct pipeline

on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish Docker image
      run: |
        docker build . --pull --tag ${IMAGE}:${TAG}
        docker push ${IMAGE}:${TAG}
#    - name: Deploy to prod-gcp
#      uses: nais/deploy/actions/deploy@master
#      env:
#        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#        CLUSTER: prod-gcp
#        RESOURCE: .nais/naisjob_stage.yaml,.nais/naisjob_dataproducts.yaml
    - name: Edit image tag in dag file
      run: |
        sed -i "s~$IMAGE:.*~$IMAGE:$TAG\"~g" dags/metrikker-datamarkedsplassen.py
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add dags/metrikker-datamarkedsplassen.py
        git commit -m "Updated image tag in metrikker-markedsplassen dag to ${TAG}"
        git push

