name: Deploy metrics dataproduct pipeline

on: push

env:
  IMAGE: navikt/nada-metrics
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish Docker image
      run: |
        docker build . --pull --tag ${IMAGE}:${TAG}
        docker push ${IMAGE}:${TAG}
    - name: Deploy to prod-gcp
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-gcp
        RESOURCE: .nais/naisjob.yaml
