name: Deploy data transfer Knorten

on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb # Use commit-sha1 instead of tag for security concerns
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish Docker image
      run: |
        docker build . --pull --tag ${IMAGE}
        docker push ${IMAGE}
    - name: Deploy to prod-gcp
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: prod-gcp
        RESOURCE: .nais/naisjob.yaml,.nais/alert.yaml
