name: Deploy metrics dataproduct pipeline

on: push

env:
  IMAGE: navikt/nada-metrics
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish Docker image
      run: |
        docker build . --pull --tag ${IMAGE}:${TAG}
        docker push ${IMAGE}:${TAG}
#    - name: Deploy to prod-gcp
#      uses: nais/deploy/actions/deploy@master
#      env:
#        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#        CLUSTER: prod-gcp
#        RESOURCE: .nais/naisjob_stage.yaml,.nais/naisjob_dataproducts.yaml
    - name: Edit image tag in dag file
      run: |
        sed -i "s~$IMAGE:.*~$IMAGE:$TAG\"~g" dags/metrikker-datamarkedsplassen.py
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add dags/metrikker-datamarkedsplassen.py
        git commit -m "Updated image tag in metrikker-markedsplassen dag to ${TAG}"
        git push
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_CREDS }}
        project_id: nada-prod-6977
        export_default_credentials: true
    - name: Upload to composer bucket
      run: gsutil cp -r dags gs://europe-west1-nada-3b8c2b10-bucket
      

